name: Build Cross-Platform Plugin

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Verify Rez tool
      run: |
        if ! command -v Rez; then
          echo "❌ Rez tool not found! Installing Xcode command-line tools..."
          xcode-select --install || true  # Ignore if already installed
          echo "❌ Rez still not found after attempting install"
          exit 1
        else
          echo "✅ Rez tool found at: $(command -v Rez)"
        fi

    - name: Create Info.plist template
      run: |
        mkdir -p Examples/AEGP/Panelator
        cat > Examples/AEGP/Panelator/Info.plist.in << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleDevelopmentRegion</key>
            <string>en</string>
            <key>CFBundleExecutable</key>
            <string>${MACOSX_BUNDLE_EXECUTABLE_NAME}</string>
            <key>CFBundleIdentifier</key>
            <string>${MACOSX_BUNDLE_IDENTIFIER}</string>
            <key>CFBundleInfoDictionaryVersion</key>
            <string>6.0</string>
            <key>CFBundleName</key>
            <string>${MACOSX_BUNDLE_BUNDLE_NAME}</string>
            <key>CFBundlePackageType</key>
            <string>BNDL</string>
            <key>CFBundleShortVersionString</key>
            <string>${MACOSX_BUNDLE_SHORT_VERSION_STRING}</string>
            <key>CFBundleVersion</key>
            <string>${MACOSX_BUNDLE_BUNDLE_VERSION}</string>
            <key>CSResourcesFileMapped</key>
            <true/>
            <key>LSMinimumSystemVersion</key>
            <string>12.0</string>
        </dict>
        </plist>
        EOF

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..

 
    - name: Build plugin
      working-directory: build
      run: cmake --build . --config Release

    - name: Verify PkgInfo
      working-directory: build
      run: |
        PLUGIN_PATH=$(find . -name "*.plugin" | head -1)
        if [ -n "$PLUGIN_PATH" ]; then
          CONTENTS_PATH="$PLUGIN_PATH/Contents"
          PKGINFO_PATH="$CONTENTS_PATH/PkgInfo"
          if [ -d "$CONTENTS_PATH" ]; then
            echo "✅ Contents dir exists"
          else
            echo "❌ Contents dir missing"
            find "$PLUGIN_PATH" -ls
            exit 1
          fi
          if [ -f "$PKGINFO_PATH" ]; then
            echo "✅ PkgInfo present at $PKGINFO_PATH"
            echo "Contents (hex):"
            xxd "$PKGINFO_PATH"
            echo "Contents (string):"
            cat -v "$PKGINFO_PATH"
          else
            echo "❌ PkgInfo NOT FOUND at $PKGINFO_PATH"
            find "$CONTENTS_PATH" -type f -ls  # List all Contents files for debug
            exit 1
          fi
          echo "Full bundle structure:"
          find "$PLUGIN_PATH" -type d -ls
          find "$PLUGIN_PATH" -type f -ls
        else
          echo "❌ No plugin bundle found"
          exit 1
        fi

    - name: Verify build
      working-directory: build
      run: |
        echo "Build artifacts:"
        find . -name "*.plugin" -exec ls -la {} \;
        find . -name "*.plugin" -exec file {} \;

        PLUGIN_PATH=$(find . -name "*.plugin" | head -1)
        if [ -n "$PLUGIN_PATH" ]; then
            echo "Plugin bundle contents:"
            find "$PLUGIN_PATH" -type f -exec ls -la {} \;

            echo "Executable dependencies:"
            find "$PLUGIN_PATH" -name "AEPathLink" -exec otool -L {} \; || true
        fi

    - name: Debug PiPL resource
      run: |
        echo "Checking for AEPathLink.r, AEConfig.h, and AE_General.r:"
        find Examples/AEGP/Panelator -name "AEPathLink.r" -ls
        find Examples/Headers -name "AEConfig.h" -ls
        find Examples/Resources -name "AE_General.r" -ls
        if [ -f "Examples/AEGP/Panelator/Win/AEPathLink.r" ] && [ -f "Examples/Headers/AEConfig.h" ] && [ -f "Examples/Resources/AE_General.r" ]; then
          echo "Contents of AEPathLink.r:"
          cat Examples/AEGP/Panelator/Win/AEPathLink.r
          echo "Contents of AE_General.r (first 20 lines):"
          cat Examples/Resources/AE_General.r | head -n 20
          echo "Attempting to run Rez manually:"
          Rez -useDF -d DEBUG=1 -i Examples/Headers -i Examples/Resources -i /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ Examples/AEGP/Panelator/Win/AEPathLink.r -o build/AEPathLink.rsrc > build/rez_stdout.log 2> build/rez_stderr.log
          if [ $? -eq 0 ] && [ -s build/AEPathLink.rsrc ]; then
            echo "✅ Rez succeeded, AEPathLink.rsrc created:"
            ls -l build/AEPathLink.rsrc
            xxd build/AEPathLink.rsrc | head -20 > build/rsrc_hexdump.log
            cat build/rsrc_hexdump.log
            echo "Rez stdout:"
            cat build/rez_stdout.log
            echo "Rez stderr (if any):"
            cat build/rez_stderr.log
            echo "Attempting DeRez (non-critical):"
            DeRez build/AEPathLink.rsrc > build/derez_output.log 2> build/derez_error.log || {
              echo "⚠️ DeRez failed (continuing)"
              cat build/derez_error.log
            }
            if [ -f build/derez_output.log ]; then
              echo "DeRez output (if any):"
              cat build/derez_output.log
            fi
          else
            echo "❌ Rez failed or AEPathLink.rsrc is empty"
            cat build/rez_stdout.log
            cat build/rez_stderr.log
            ls -l build/AEPathLink.rsrc || echo "File missing"
            exit 1
          fi
        else
          echo "❌ AEPathLink.r, AEConfig.h, or AE_General.r not found"
          exit 1
        fi    

    - name: Verify Bundle Structure
      run: |
        echo "Checking bundle structure:"
        find build/AEPathLink.plugin -type f -ls || echo "Bundle not fully created"
        if [ -f "build/AEPathLink.plugin/Contents/PkgInfo" ]; then
          echo "PkgInfo contents:"
          hexdump -C build/AEPathLink.plugin/Contents/PkgInfo
          echo "PkgInfo size:"
          stat -f%z build/AEPathLink.plugin/Contents/PkgInfo
        else
          echo "❌ PkgInfo not found"
        fi
        if [ -f "build/AEPathLink.plugin/Contents/Resources/AEPathLink.rsrc" ]; then
          echo "AEPathLink.rsrc contents (first 20 lines):"
          xxd build/AEPathLink.plugin/Contents/Resources/AEPathLink.rsrc | head -20
        else
          echo "❌ AEPathLink.rsrc not found in bundle"
        fi
    
    - name: Verify PiPL resource
      working-directory: build
      run: |
        if [ ! -f AEPathLink.plugin/Contents/Resources/AEPathLink.rsrc ]; then
          echo "❌ PiPL .rsrc file not found!"
          exit 1
        else
          echo "✅ PiPL .rsrc present"
        fi

    - name: Package for distribution
      working-directory: build
      run: |
        PLUGIN_PATH=$(find . -name "*.plugin" | head -1)
        if [ -n "$PLUGIN_PATH" ]; then
            cd "$(dirname "$PLUGIN_PATH")"
            zip -r "$GITHUB_WORKSPACE/AEPathLink-macOS.zip" "$(basename "$PLUGIN_PATH")"
        else
            echo "No plugin found!"
            exit 1
        fi



    - name: Upload plugin
      uses: actions/upload-artifact@v4
      with:
        name: AEPathLink-macOS
        path: ${{ github.workspace }}/AEPathLink-macOS.zip
        retention-days: 30